### ISSUE TITLE
Possible size race

### ISSUE THREAD

**Issue by gagern** [CindyJS/website#13]
The current website uses `app.css` to choose dimensions for some of the examples. At least in theory this leads to a race condition: if the CSS isn't loaded and applied by the time a CindyJS widget launches, it will have the wrong idea about its dimensions. And until we [implement a resize sensor](https://github.com/CindyJS/CindyJS/blob/e145b1da9c3fbabdc5376685dce8f09f636bb347/src/js/Setup.js#L150-L151), we may fail to recover from this. So far I haven't managed to actually produce this scenario since `Cindy.js` takes longer to load than `app.css`. But with a flaky mobile connection I think this might well happen to some of our potential users.

One possible solution would be inlining the relevant part of the stylesheet into the HTML template, so that it is guaranteed to be available by the time the widgets start. Or we could inline the dimensions in the style attribute for each widget. Another possible solution would be implementing that resize sensor as suggested.

If you know of a way to ensure that a CSS got applied, we could defer widget launches while waiting for that event, but last I looked I couldn't find a suitable event for this. If I remember correctly, Firefox fires onload events for its `<link>` tags the moment they have loaded, but applies them asynchroneously after that event got processed.

**Comment by kortenkamp** [comment]
I think the proper solution is indeed to implement resize handling... this can also happen for example when turning a mobile device from landscape to portrait.

**Comment by gagern** [comment]
@kortenkamp: Rotating a mobile device should trigger a resize event, imo, which [we already handle](https://github.com/CindyJS/CindyJS/blob/e145b1da9c3fbabdc5376685dce8f09f636bb347/src/js/Events.js#L276-L281). So the problem is really only for situations where the widget box size changes even though the browser window size remains the same.

**Comment by kortenkamp** [comment]
So it is just a matter of detecting the size change and triggering the same resize event?

**Comment by gagern** [comment]
Exactly. Slightly hampered by the fact that HTML5 apparently has no clean mechanism to achieve this.

**Comment by richter-gebert** [comment]
Nächste Prinzipielle Frage.

Ist es ok, wenn ich pro Zeile im Moment 5 Beispiele plane?


Auf Desktop und iPad sieht das vernünftig aus (auch hochkant).
Auf iPhone muss man aber eigentlich umbrechen. 
Das macht dann halt entweder 1-1-1-1-1 oder 2-2-1 oder 3-2
Könnte ich aber mit leben.

4 oder 6 Beispiele fände ich eigentlich zu wenig oder zu viel.

Sagt mal was Ihr meint.

cu

Jürgen




--------------------------------------
Prof. Jürgen Richter-Gebert
Geometrie und Visualisierung
Zentrum Mathematik --- TU München
Boltzmannstr. 3
85747 Garching bei München
Tel: 089/28918354, Sekr: 089/28918359
e-mail: richter@ma.tum.de

**Comment by gagern** [comment]
Closing as per https://github.com/CindyJS/CindyJS/issues/435.
