### ISSUE TITLE
Prepare for MathJax CDN shutdown

### ISSUE THREAD

**Issue by gagern** [CindyJS/website#56]
According to https://www.mathjax.org/cdn-shutting-down/, `cdn.mathjax.org` is shutting down by the end of April and we should be migrating away from that. A suitable `cdnjs.cloudflare.com` configuration might be our best bet. Right now there are three gallery pages using that host, one conference presentation and two examples shipped with the source tree.

* [website/src/gallery/main/JuliaConjugated/description.md](https://github.com/CindyJS/website/blob/032cdf42973cf67d96cf8da7d6d355c3ce22b2f0/src/gallery/main/JuliaConjugated/description.md#L1)
* [website/src/gallery/cindygl/ComplexExplorer/description.md](https://github.com/CindyJS/website/blob/032957ddc1da42d9b100d42fd51bbaeec43e6e47/src/gallery/cindygl/ComplexExplorer/description.md#L1)
* [website/src/gallery/main/ComplexExplorer/description.md](https://github.com/CindyJS/website/blob/032957ddc1da42d9b100d42fd51bbaeec43e6e47/src/gallery/main/ComplexExplorer/description.md#L1)
* [website/src/asis/pub/2016-icms/plugins/EuclidMJ.html](https://github.com/CindyJS/website/blob/032cdf42973cf67d96cf8da7d6d355c3ce22b2f0/src/asis/pub/2016-icms/plugins/EuclidMJ.html#L8)
* [CindyJS/examples/19_EuclidsAlgX2.html](https://github.com/CindyJS/CindyJS/blob/6dfb005098dec0642f035935669fa38c348a7557/examples/19_EuclidsAlgX2.html#L10)
* [CindyJS/examples/cindygl/22_explorer.html](https://github.com/CindyJS/CindyJS/blob/6dfb005098dec0642f035935669fa38c348a7557/examples/cindygl/22_explorer.html#L11)

**Comment by montaga** [comment]
I committed the replacement of all the dependencies from `cdn.mathjax.org` with `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js` directly into the master.
